APP_PASSWORD = "changez_moi_pour_un_vrai_mot_de_passe"

[doinsport]
login = "email@example.com"
password = "xxx"
club_id = "f520b68c-d5dd-4fd2-84b0-3e0742a771a2"
activity_id = "541b8d8a-3ce2-4f46-913c-5e6e4d9b5dea"
category_id = "190e89c2-98a1-4f3b-a23d-df5c921e9324"

[google_chat]
webhook_prod = "https://chat.googleapis.com/..."
webhook_test = "https://chat.googleapis.com/..."
